### ISSUE TITLE
GAIL could not work on Pendulum-v0

### ISSUE THREAD

**Issue by zhihaocheng** [keiohta/tf2rl#103]
I followed the instructions in this repository to generate expert data using SAC for Pendulum-v0, and then use GAIL to conduct imitation learning. But the results of GAIL turn to be NaN. Could you please help me?

**Comment by zhihaocheng** [comment]
I find that my problem is similar to [https://github.com/keiohta/tf2rl/issues/92](url). After the installation of tensorflow 2.0.0，I am able to use spectral normalization. But this problem is quite strange because ordinary GAIL is supposed to work.

**Comment by keiohta** [comment]
Hi @zhihaocheng , I uploaded codes that support tf2.3 now to PyPI. Can you upgrade tf2rl and try again?

If you still encounter the same problem, please provide more details:
- OS
- TensorFlow version
- Full message of the error

**Comment by zhihaocheng** [comment]
Hi @keiohta , thanks for your help. I have tried tf2.3 and the newest tf2rl, but it could not work. Details are presented below.

**OS**: CentOS Linux release 7.2 (Final).
**Tensorflow**: tensorflow-cpu 2.3.0, tensorflow 2.3.0.
**tf2rl**: 0.1.15.
**Full error**：
Traceback (most recent call last):
  File "examples/run_gail_ddpg.py", line 39, in <module>
    gpu=args.gpu)
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tf2rl/algos/gail.py", line 50, in __init__
    units=units, enable_sn=enable_sn)
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tf2rl/algos/gail.py", line 25, in __init__
    self([dummy_state, dummy_action])
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tf2rl/algos/gail.py", line 29, in call
    features = self.l1(features)
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/zhc/anaconda3/envs/dads-env/lib/python3.6/site-packages/tf2rl/networks/spectral_norm_dense.py", line 50, in call
    rank = common_shapes.rank(inputs)
AttributeError: module 'tensorflow.python.framework.common_shapes' has no attribute 'rank'.

**Comment by keiohta** [comment]
Hi @zhihaocheng , I'm working on this at [this branch](https://github.com/keiohta/tf2rl/tree/issue-103), but hasn't resolved the error.

In the mean time, please use tf < 2.3 or not use Spectral Normalization. (The above error has been resolved but I encountered an other error.)

**Comment by keiohta** [comment]
Hi @zhihaocheng , I confirmed the GAIL + SN works with TF2.3 at the latest master.
Following is the command I used for test.

```bash
# Generate expert data
$ python examples/run_ddpg.py --max-steps 20000 --test-interval 20000 --save-test-path --test-episodes 50 --gpu -1

# TF2.0
$ conda activate tf2.0
$ python examples/run_gail_ddpg.py --max-steps 50000 --expert-path-dir results/20200829T150459.520911_DDPG_expert_paths --dir-suffix _TF20 --gpu -1
$ python examples/run_gail_ddpg.py --max-steps 50000 --expert-path-dir results/20200829T150459.520911_DDPG_expert_paths --enable-sn --dir-suffix _TF20_SN --gpu -1

# TF2.3
$ conda activate tf2.3
$ python examples/run_gail_ddpg.py --max-steps 50000 --expert-path-dir results/20200829T150459.520911_DDPG_expert_paths --dir-suffix _TF23 --gpu -1
$ python examples/run_gail_ddpg.py --max-steps 50000 --expert-path-dir results/20200829T150459.520911_DDPG_expert_paths --enable-sn --dir-suffix _TF23_SN --gpu -1
$ 
```

And the resulted TensorBoard output is below:
![Screen Shot 2020-08-29 at 21 19 48](https://user-images.githubusercontent.com/7234712/91636670-695f9d80-ea3d-11ea-8fa3-d046443c5441.png)

**Comment by zhihaocheng** [comment]
Thanks a lot @keiohta
